# Generated by Django 5.2 on 2025-05-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0003_city_province_recipientaddress_city_city_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
    ]
