# Generated by Django 5.2 on 2025-05-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinvoice',
            options={'verbose_name': 'پرداخت قبض', 'verbose_name_plural': 'پرداخت قبض ها'},
        ),
    ]
