# Generated by Django 5.2 on 2025-04-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0001_initial'),
        ('Services', '0006_remove_recepientservicerequest_accountant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicescore',
            name='service_request',
        ),
        migrations.AddField(
            model_name='servicescore',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Services.service', verbose_name='سرویس'),
            preserve_default=False,
        ),
    ]
