# Generated by Django 5.2 on 2025-04-25 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', models.TextField(blank=True, help_text='توضیح مختصر درباره خودتان', verbose_name='بیوگرافی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/profile_pics/providers/', verbose_name='تصویر پروفایل')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سال\u200cهای تجربه')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل خدمات دهنده',
                'verbose_name_plural': 'پروفایل خدمات دهندگان',
            },
        ),
        migrations.CreateModel(
            name='ServiceRecipientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', models.TextField(blank=True, help_text='توضیح مختصر درباره خودتان', verbose_name='بیوگرافی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/profile_pics/recipients/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل خدمات گیرنده',
                'verbose_name_plural': 'پروفایل خدمات گیرندگان',
            },
        ),
    ]
