# Generated by Django 5.2 on 2025-04-25 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', models.TextField(blank=True, help_text='توضیح مختصر درباره خودتان', verbose_name='بیوگرافی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/profile_pics/admin/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل ادمین',
                'verbose_name_plural': 'پروفایل ادمین ها',
            },
        ),
        migrations.CreateModel(
            name='ServiceSupportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', models.TextField(blank=True, help_text='توضیح مختصر درباره خودتان', verbose_name='بیوگرافی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/profile_pics/support/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل پشتیبان',
                'verbose_name_plural': 'پروفایل پشتیبان ها',
            },
        ),
    ]
