# Generated by Django 5.2 on 2025-05-04 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_serviceadminprofile_servicesupportprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceAdminProfile',
            new_name='AdminProfile',
        ),
        migrations.RenameModel(
            old_name='ServiceSupportProfile',
            new_name='SupportProfile',
        ),
    ]
