# Generated by Django 5.2 on 2025-04-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCardInFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='شماره ملی')),
                ('id_card', models.FileField(blank=True, help_text='بارگذاری تصویر/اسکن کارت ملی', null=True, upload_to='Users/id_cards/', verbose_name='کارت ملی')),
                ('id_card_status', models.CharField(choices=[('P', 'درحال برسی'), ('V', 'تایید شده'), ('R', 'رد شده')], default='P', help_text='وضعیت بررسی کارت ملی', max_length=1, verbose_name='وضعیت کارت ملی')),
            ],
            options={
                'verbose_name': 'اطلاعات carteau ملی',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_card_info', to='Users.idcardinformation', verbose_name='اطلاعات کارت ملی'),
        ),
    ]
