# Generated by Django 5.2 on 2025-05-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_idcardinformation_user_id_card_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idcardinformation',
            options={'verbose_name': 'اطلاعات کارت ملی', 'verbose_name_plural': 'اطلاعات کارت ملی ها'},
        ),
    ]
