# Generated by Django 5.2 on 2025-04-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Industries', '0002_serviceindustry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceindustry',
            name='industry',
        ),
    ]
