# Generated by Django 5.2 on 2025-04-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Industries', '0003_remove_serviceindustry_industry'),
        ('Services', '0007_remove_recepientservicerequestemployees_recipient_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceIndustry',
        ),
    ]
