# Generated by Django 5.2 on 2025-05-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industries', '0004_delete_serviceindustry'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='price_per_service',
            field=models.BigIntegerField(default=0, verbose_name='قیمت هر سرویس'),
        ),
    ]
