# Generated by Django 5.2 on 2025-05-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Industries', '0005_industry_price_per_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name'], 'verbose_name': 'صنعت', 'verbose_name_plural': 'صنعت ها'},
        ),
    ]
