# Generated by Django 5.2 on 2025-05-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0002_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'قبض', 'verbose_name_plural': 'قبض ها'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'آیتم قبض', 'verbose_name_plural': 'آیتم\u200cهای قبض'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور قبض'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Invoices.invoice', verbose_name='قبض مربوطه'),
        ),
    ]
