# Generated by Django 5.2 on 2025-04-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EXP', 'Expired'), ('ACT', 'Active')], default='ACT', max_length=3)),
                ('token', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف',
            },
        ),
        migrations.CreateModel(
            name='UserRegisterOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('password_conf', models.CharField(max_length=255)),
                ('user_type', models.CharField(default='JS', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_otps', to='Authentication.onetimepassword')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف ثبت نام کاربر',
            },
        ),
    ]
