# Generated by Django 5.2 on 2025-05-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OneTimePasswords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('password_conf', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف ثبت نام کاربر',
                'verbose_name_plural': 'رمز های یکبار مصرف ثبت نام کاربر',
            },
        ),
        migrations.CreateModel(
            name='UserLoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to='OneTimePasswords.onetimepassword', verbose_name='کد یکبار مصرف')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف ورود کاربر',
                'verbose_name_plural': 'رمزهای یکبار مصرف ورود کاربران',
            },
        ),
    ]
