# Generated by Django 5.2 on 2025-05-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0008_remove_company_number_of_employees_and_more'),
        ('Services', '0008_service_is_invoiced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور فاکتور')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال')),
                ('total_amount', models.BigIntegerField(default=0, verbose_name='مبلغ کل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Companies.company', verbose_name='شرکت')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت مورد')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Invoices.invoice', verbose_name='فاکتور مربوطه')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invice_item', to='Services.service', verbose_name='سرویس')),
            ],
        ),
    ]
