# Generated by Django 5.2 on 2025-05-27 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0002_initial'),
        ('Services', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.BigIntegerField(default=0, verbose_name='مبلغ کل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('deadline', models.DateTimeField(null=True, verbose_name='مهلت پرداخت')),
                ('deadline_status', models.CharField(choices=[('AC', 'فعال'), ('EX', 'منقضی شده')], default='AC', max_length=2, verbose_name='وضعیت مهلت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور قبض')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Companies.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'قبض',
                'verbose_name_plural': 'قبض ها',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت مورد')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Invoices.invoice', verbose_name='قبض مربوطه')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invoice_item', to='Services.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'آیتم قبض',
                'verbose_name_plural': 'آیتم\u200cهای قبض',
            },
        ),
    ]
