# Generated by Django 5.2 on 2025-04-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0002_companyvalidationstatus'),
        ('Industries', '0002_serviceindustry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, verbose_name='اسلاگ')),
                ('descriptions', models.TextField(verbose_name='توضحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_compay', to='Companies.company', verbose_name='شرکت')),
                ('service_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='Industries.serviceindustry', verbose_name='صنعت سرویس')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
    ]
