# Generated by Django 5.2 on 2025-04-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepientServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, verbose_name='اسلاگ')),
                ('descriptions', models.TextField(verbose_name='توضحات')),
                ('status', models.CharField(choices=[('PA', 'پرداخت شده'), ('UP', 'پرداخت نشده'), ('FA', 'ناموفق')], default='UP', max_length=3, verbose_name='وضعیت پرداخت')),
                ('started_at', models.DateTimeField(null=True, verbose_name='شروع شده')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='تمام شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serivice_recepient', to='Services.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'سرویس درخواست شده',
                'verbose_name_plural': 'سرویس های درخواست شده',
            },
        ),
    ]
