# Generated by Django 5.2 on 2025-04-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_companyvalidationstatus'),
        ('Industries', '0002_serviceindustry'),
        ('Services', '0003_recepientservicerequest_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepientservicerequest',
            options={'verbose_name': 'درخواست سرویس', 'verbose_name_plural': 'درخواست\u200cهای سرویس'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس\u200cها'},
        ),
        migrations.RenameField(
            model_name='recepientservicerequest',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='recepientservicerequest',
            name='service_status',
            field=models.CharField(choices=[('PE', 'درحال بررسی'), ('IP', 'درحال اجرا'), ('FI', 'تمام شده'), ('CA', 'کنسل شده'), ('FA', 'شکست خورده'), ('RE', 'گزارش شده')], default='PE', max_length=3, verbose_name='وضعیت سرویس'),
        ),
        migrations.AlterField(
            model_name='recepientservicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='recepientservicerequest',
            name='descriptions',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='recepientservicerequest',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='recepientservicerequest',
            name='started_at',
            field=models.DateTimeField(null=True, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='recepientservicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='service',
            name='descriptions',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Industries.serviceindustry', verbose_name='صنعت سرویس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
