# Generated by Django 5.2 on 2025-04-29 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_recepientservicerequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepientservicerequest',
            name='accountant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_accountant', to=settings.AUTH_USER_MODEL, verbose_name='حسابدار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepientservicerequest',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_expert', to=settings.AUTH_USER_MODEL, verbose_name='متخصص'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepientservicerequest',
            name='receptionist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_receptionist', to=settings.AUTH_USER_MODEL, verbose_name='منشی'),
            preserve_default=False,
        ),
    ]
