# Generated by Django 5.2 on 2025-05-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_service_is_invoiced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceContent',
        ),
    ]
