# Generated by Django 5.2 on 2025-05-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_rename_serviceemployees_serviceemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CA', 'نقدی'), ('TR', 'کارت به کارت')], max_length=20, null=True, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='service',
            name='transaction_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='Services/transaction_screenshots/', verbose_name='تصویر فاکتور تراکنش'),
        ),
    ]
