# Generated by Django 5.2 on 2025-05-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0015_companycard'),
        ('Services', '0011_service_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='company_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_card', to='Companies.companycard', verbose_name='کارت'),
        ),
    ]
