# Generated by Django 5.2 on 2025-04-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Industry/industries-icon/', verbose_name='آیکون')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_service', to='Industries.industry', verbose_name='صنعت')),
            ],
            options={
                'verbose_name': 'سرویس صنعت',
                'verbose_name_plural': 'سرویس های صنعت',
                'ordering': ['-industry'],
            },
        ),
    ]
