# Generated by Django 5.2 on 2025-05-13 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0002_userloginotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordOneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.onetimepassword', verbose_name='کد اعتبار سنجی')),
            ],
            options={
                'verbose_name': 'کد اعتبار سنجی رمزعبور',
                'verbose_name_plural': 'کد های اعتبار سنجی رمزعبور',
            },
        ),
    ]
