# Generated by Django 5.2 on 2025-05-15 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_resetpasswordonetimepassword_otp'),
        ('OneTimePasswords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordonetimepassword',
            name='otp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password', to='OneTimePasswords.onetimepassword', verbose_name='کد اعتبار سنجی'),
        ),
    ]
