# Generated by Django 5.2 on 2025-05-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_resetpasswordonetimepassword_user'),
        ('Authentication', '0002_userloginotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordonetimepassword',
            name='otp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password', to='Authentication.onetimepassword', verbose_name='کد اعتبار سنجی'),
        ),
    ]
