# Generated by Django 5.2 on 2025-04-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipientaddress',
            options={'verbose_name': 'آدرس مشتری', 'verbose_name_plural': 'آدرس های مشتری ها'},
        ),
    ]
