# Generated by Django 5.2 on 2025-05-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipientaddress',
            old_name='Recipient',
            new_name='recipient',
        ),
    ]
