# Generated by Django 5.2 on 2025-05-27 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(verbose_name='مبلغ پرداختی')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه تراکنش')),
                ('payment_status', models.CharField(choices=[('PE', 'در انتظار پرداخت'), ('SU', 'موفق'), ('FA', 'ناموفق')], default='PE', max_length=3, verbose_name='وضعیت پرداخت')),
                ('authority', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoice', to='Invoices.invoice', verbose_name='فاکتور پرداخت')),
            ],
            options={
                'verbose_name': 'پرداخت قبض',
                'verbose_name_plural': 'پرداخت قبض ها',
            },
        ),
    ]
