# Generated by Django 5.2 on 2025-05-15 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_resetpasswordonetimepassword_otp'),
        ('Authentication', '0002_userloginotp'),
        ('OneTimePasswords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterotp',
            name='otp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_otps', to='OneTimePasswords.onetimepassword'),
        ),
        migrations.AlterField(
            model_name='userloginotp',
            name='otp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to='OneTimePasswords.onetimepassword', verbose_name='کد یکبار مصرف'),
        ),
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
