# Generated by Django 5.2 on 2025-05-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_userregisterotp_otp_alter_userloginotp_otp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregisterotp',
            options={'verbose_name': 'رمز یکبار مصرف ثبت نام کاربر', 'verbose_name_plural': 'رمز های یکبار مصرف ثبت نام کاربر'},
        ),
    ]
