# Generated by Django 5.2 on 2025-05-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('icon', models.FileField(blank=True, null=True, upload_to='Items/first/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'آیتم یک',
                'verbose_name_plural': 'آیتم های یک',
            },
        ),
        migrations.CreateModel(
            name='SecondItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('icon', models.FileField(blank=True, null=True, upload_to='Items/second/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'آیتم دو',
                'verbose_name_plural': 'آیتم های دو',
            },
        ),
    ]
