# Generated by Django 5.2 on 2025-05-27 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='آیدیه سرویس')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('image', models.FileField(upload_to='Services/image/')),
                ('payment_status', models.CharField(choices=[('PA', 'پرداخت شده'), ('UP', 'پرداخت نشده'), ('FA', 'ناموفق')], default='UP', max_length=3, verbose_name='وضعیت پرداخت')),
                ('service_status', models.CharField(choices=[('PE', 'درحال بررسی'), ('IP', 'درحال اجرا'), ('FI', 'تمام شده'), ('CA', 'کنسل شده'), ('FA', 'شکست خورده'), ('RE', 'گزارش شده')], default='PE', max_length=3, verbose_name='وضعیت سرویس')),
                ('payment_method', models.CharField(blank=True, choices=[('CA', 'نقدی'), ('TR', 'کارت به کارت')], max_length=20, null=True, verbose_name='روش پرداخت')),
                ('transaction_screenshot', models.ImageField(blank=True, null=True, upload_to='Services/transaction_screenshots/', verbose_name='تصویر فاکتور تراکنش')),
                ('is_invoiced', models.BooleanField(default=False, verbose_name='به فاکتور اضافه شده')),
                ('started_at', models.DateTimeField(null=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='زمان پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_services', to='Companies.companyaccountant', verbose_name='حسابدار')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company', to='Companies.company', verbose_name='شرکت')),
                ('company_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_card', to='Companies.companycard', verbose_name='کارت')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_services', to='Companies.companyexpert', verbose_name='متخصص')),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_services', to='Companies.companyreceptionist', verbose_name='منشی سرویس')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس\u200cها',
            },
        ),
    ]
