# Generated by Django 5.2 on 2025-05-24 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Addresses', '0002_initial'),
        ('Companies', '0002_initial'),
        ('Services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepient_services', to=settings.AUTH_USER_MODEL, verbose_name='سرویس گیرنده'),
        ),
        migrations.AddField(
            model_name='service',
            name='recipient_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_addresses', to='Addresses.recipientaddress', verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL, verbose_name='سرویس دهنده'),
        ),
        migrations.AddField(
            model_name='serviceemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company_worker', to='Companies.companyemployee', verbose_name='کارمند شرکت'),
        ),
        migrations.AddField(
            model_name='serviceemployee',
            name='recipient_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_workers', to='Services.service', verbose_name='سرویس درخواست شده'),
        ),
    ]
