# Generated by Django 5.2 on 2025-05-27 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Addresses', '0002_initial'),
        ('Services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepient_services', to=settings.AUTH_USER_MODEL, verbose_name='سرویس گیرنده'),
        ),
        migrations.AddField(
            model_name='service',
            name='recipient_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_addresses', to='Addresses.recipientaddress', verbose_name='آدرس'),
        ),
    ]
