# Generated by Django 5.2 on 2025-05-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceEmployee',
        ),
    ]
