# Generated by Django 5.2 on 2025-05-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_initial'),
        ('Services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='company_card',
        ),
        migrations.RemoveField(
            model_name='service',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='service',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='transaction_screenshot',
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('payment_status', models.CharField(choices=[('PA', 'پرداخت شده'), ('UP', 'پرداخت نشده'), ('FA', 'ناموفق')], default='UP', max_length=3, verbose_name='وضعیت پرداخت')),
                ('payment_method', models.CharField(blank=True, choices=[('CA', 'نقدی'), ('TR', 'کارت به کارت')], max_length=20, null=True, verbose_name='روش پرداخت')),
                ('transaction_screenshot', models.ImageField(blank=True, null=True, upload_to='Services/transaction_screenshots/', verbose_name='تصویر فاکتور تراکنش')),
                ('paied_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('company_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_card', to='Companies.companycard', verbose_name='کارت')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_payment', to='Services.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'اطلاعات پرداخت سرویس',
                'verbose_name_plural': 'اطلاعات پرداخت سرویس ها',
            },
        ),
    ]
