# Generated by Django 5.2 on 2025-04-28 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_alter_recipientaddress_options'),
        ('Services', '0002_recepientservicerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepientservicerequest',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepient_services', to=settings.AUTH_USER_MODEL, verbose_name='سرویس گیرنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepientservicerequest',
            name='recipient_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_addresses', to='Addresses.recipientaddress', verbose_name='آدرس'),
            preserve_default=False,
        ),
    ]
