# Generated by Django 5.2 on 2025-05-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_initial'),
        ('Services', '0004_service_first_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_services', to='Companies.companyaccountant', verbose_name='حسابدار'),
        ),
        migrations.AlterField(
            model_name='service',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_services', to='Companies.companyexpert', verbose_name='متخصص'),
        ),
        migrations.AlterField(
            model_name='service',
            name='receptionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptionist_services', to='Companies.companyreceptionist', verbose_name='منشی سرویس'),
        ),
    ]
