# Generated by Django 5.2 on 2025-04-29 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0003_companyemployee'),
        ('Services', '0005_recepientservicerequest_accountant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepientservicerequest',
            name='accountant',
        ),
        migrations.RemoveField(
            model_name='recepientservicerequest',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='recepientservicerequest',
            name='receptionist',
        ),
        migrations.AddField(
            model_name='recepientservicerequest',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecepientServiceRequestEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company_worker', to='Companies.companyemployee')),
                ('recipient_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_workers', to='Services.recepientservicerequest', verbose_name='سرویس درخاست شده')),
            ],
            options={
                'verbose_name': 'کارمند سرویس',
                'verbose_name_plural': 'کارمندان سرویس ها',
            },
        ),
    ]
