# Generated by Django 5.2 on 2025-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_service_accountant_alter_service_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='suggested_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پیشنهادی شروع'),
        ),
        migrations.AlterField(
            model_name='service',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='service',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع'),
        ),
    ]
