# Generated by Django 5.2 on 2025-04-30 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_alter_recipientaddress_options'),
        ('Companies', '0004_company_industry'),
        ('Scores', '0002_remove_servicescore_service_request_and_more'),
        ('Services', '0006_remove_recepientservicerequest_accountant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepientservicerequestemployees',
            name='recipient_service',
        ),
        migrations.RemoveField(
            model_name='recepientservicerequestemployees',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_industry',
        ),
        migrations.AddField(
            model_name='service',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='زمان پایان'),
        ),
        migrations.AddField(
            model_name='service',
            name='payment_status',
            field=models.CharField(choices=[('PA', 'پرداخت شده'), ('UP', 'پرداخت نشده'), ('FA', 'ناموفق')], default='UP', max_length=3, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='service',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepient_services', to=settings.AUTH_USER_MODEL, verbose_name='سرویس گیرنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='recipient_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_addresses', to='Addresses.recipientaddress', verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to=settings.AUTH_USER_MODEL, verbose_name='سرویس دهنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_status',
            field=models.CharField(choices=[('PE', 'درحال بررسی'), ('IP', 'درحال اجرا'), ('FI', 'تمام شده'), ('CA', 'کنسل شده'), ('FA', 'شکست خورده'), ('RE', 'گزارش شده')], default='PE', max_length=3, verbose_name='وضعیت سرویس'),
        ),
        migrations.AddField(
            model_name='service',
            name='started_at',
            field=models.DateTimeField(null=True, verbose_name='زمان شروع'),
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Services/content/images/', verbose_name='عکس')),
                ('video', models.FileField(blank=True, null=True, upload_to='Services/content/videos/', verbose_name='ویدیو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Content', to='Services.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'محتوای سرویس',
                'verbose_name_plural': 'محتواهای سرویس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ServiceEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='سمت کاری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company_worker', to='Companies.companyemployee', verbose_name='کارمند شرکت')),
                ('recipient_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_workers', to='Services.service', verbose_name='سرویس درخواست شده')),
            ],
            options={
                'verbose_name': 'کارمند سرویس',
                'verbose_name_plural': 'کارمندان سرویس\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='RecepientServiceRequest',
        ),
        migrations.DeleteModel(
            name='RecepientServiceRequestEmployees',
        ),
    ]
