# Generated by Django 5.2 on 2025-05-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_remove_recepientservicerequestemployees_recipient_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='به فاکتور اضافه شده'),
        ),
    ]
