# Generated by Django 5.2 on 2025-05-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0012_alter_companyvalidationstatus_business_license'),
        ('Services', '0009_delete_servicecontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceEmployees',
            new_name='ServiceEmployee',
        ),
    ]
