# Generated by Django 5.2 on 2025-05-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneTimePasswords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimepassword',
            options={'verbose_name': 'رمز یکبار مصرف', 'verbose_name_plural': 'رمز های یکبار مصرف'},
        ),
    ]
