# Generated by Django 5.2 on 2025-04-26 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValidationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_license', models.FileField(upload_to='Companies/Validations/', verbose_name='جواز کسب')),
                ('tax_certificate', models.FileField(upload_to='Companies/Validations/', verbose_name='گواهی مالیاتی')),
                ('safety_clearance', models.FileField(upload_to='Companies/Validations/', verbose_name='مجوز ایمنی')),
                ('compliance_certificate', models.FileField(upload_to='Companies/Validations/', verbose_name='گواهینامه انطباق')),
                ('business_license_status', models.BooleanField(default=False, verbose_name='جواز کسب')),
                ('tax_certificate_status', models.BooleanField(default=False, verbose_name='گواهی مالیاتی')),
                ('safety_clearance_status', models.BooleanField(default=False, verbose_name='مجوز ایمنی')),
                ('compliance_certificate_status', models.BooleanField(default=False, verbose_name='گواهینامه انطباق')),
                ('overall_status', models.CharField(choices=[('P', 'درانتظار'), ('A', 'تایید شده'), ('R', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت کلی')),
                ('validated_at', models.DateTimeField(blank=True, help_text='زمان تایید شرکت توسط ادمین.', null=True, verbose_name='تاریخ تایید')),
                ('validation_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_status', to='Companies.company', verbose_name='شرکت')),
                ('validated_by', models.ForeignKey(blank=True, help_text='ادمینی که شرکت را تایید کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_companies', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط')),
            ],
            options={
                'verbose_name': 'وضعیت شرکت ها',
            },
        ),
    ]
