# Generated by Django 5.2 on 2025-05-02 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0008_remove_company_number_of_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('icon', models.FileField(blank=True, null=True, upload_to='Companies/items/first/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'آیتم یک',
                'verbose_name_plural': 'آیتم های یک',
            },
        ),
        migrations.CreateModel(
            name='SecondItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('icon', models.FileField(blank=True, null=True, upload_to='Companies/items/second/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'آیتم دو',
                'verbose_name_plural': 'آیتم های دو',
            },
        ),
        migrations.AlterModelOptions(
            name='companyvalidationstatus',
            options={'verbose_name': 'وضعیت شرکت', 'verbose_name_plural': 'وضعیت شرکت ها'},
        ),
        migrations.CreateModel(
            name='CompanyFirstItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_second_item', to='Companies.company', verbose_name='شرکت')),
                ('second_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_second_item', to='Companies.seconditem', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'آیتم دوم شرکت',
                'verbose_name_plural': 'آیتم های دوم شرکت',
            },
        ),
    ]
