# Generated by Django 5.2 on 2025-05-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0010_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyfirstitem',
            options={'verbose_name': 'آیتم اول شرکت', 'verbose_name_plural': 'آیتم های اول شرکت'},
        ),
        migrations.RemoveField(
            model_name='companyfirstitem',
            name='second_item',
        ),
        migrations.AddField(
            model_name='companyfirstitem',
            name='first_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_first_item', to='Companies.firstitem', verbose_name='آیتم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyfirstitem',
            name='compay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_first_item', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.CreateModel(
            name='CompanySecondItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_second_item', to='Companies.company', verbose_name='شرکت')),
                ('second_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_second_item', to='Companies.seconditem', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'آیتم دوم شرکت',
                'verbose_name_plural': 'آیتم های دوم شرکت',
            },
        ),
    ]
