# Generated by Django 5.2 on 2025-05-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0011_alter_companyfirstitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvalidationstatus',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='Companies/Validations/', verbose_name='جواز کسب'),
        ),
    ]
