# Generated by Django 5.2 on 2025-05-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0013_remove_company_address_companyaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Companies.company', verbose_name='خدمات گیرنده'),
        ),
    ]
