# Generated by Django 5.2 on 2025-05-14 05:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0014_alter_companyaddress_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='Card number must consist of exactly 16 digits.', regex='^\\d{16}$')], verbose_name='شماره کارت')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='مالک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_card', to='Companies.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'کارت شرکت',
                'verbose_name_plural': 'کارت های شرکت ها',
            },
        ),
    ]
