# Generated by Django 5.2 on 2025-04-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SP', 'خدمات دهنده'), ('SC', 'خدمات گیرنده'), ('OW', 'مالک'), ('SU', 'پشتیبان'), ('AD', 'مدیر')], max_length=2, verbose_name='نوع کاربر'),
        ),
    ]
