# Generated by Django 5.2 on 2025-05-24 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام شرکت')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='لوگو')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='company/banners/', verbose_name='بنر')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='ویدئوی معرفی')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تأسیس')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینک LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='لینک Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک Instagram')),
                ('service_type', models.CharField(choices=[('IHS', 'خدمات در منزل'), ('ICS', 'خدمات در شرکت'), ('BOT', 'هر دو')], default='ICS', max_length=3, verbose_name='نوع خدمات')),
                ('is_validated', models.BooleanField(default=False, help_text='در صورت True بودن، شرکت توسط ادمین تایید شده است.', verbose_name='تایید شده توسط ادمین')),
                ('is_off_season', models.BooleanField(default=False, verbose_name='فصل تعطیلات / غیر کاری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
            ],
            options={
                'verbose_name': 'آدرس مشتری',
                'verbose_name_plural': 'آدرس های مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='Card number must consist of exactly 16 digits.', regex='^\\d{16}$')], verbose_name='شماره کارت')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='مالک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'کارت شرکت',
                'verbose_name_plural': 'کارت های شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('RE', 'منشی'), ('AC', 'حسابدار'), ('EX', 'متخصص')], max_length=2, verbose_name='موقعیت شغلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کارمند ها',
            },
        ),
        migrations.CreateModel(
            name='CompanyFirstItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'آیتم اول شرکت',
                'verbose_name_plural': 'آیتم های اول شرکت',
            },
        ),
        migrations.CreateModel(
            name='CompanySecondItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'آیتم دوم شرکت',
                'verbose_name_plural': 'آیتم های دوم شرکت',
            },
        ),
        migrations.CreateModel(
            name='CompanyValidationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='Companies/Validations/', verbose_name='جواز کسب')),
                ('business_license_status', models.BooleanField(default=False, verbose_name='جواز کسب')),
                ('overall_status', models.CharField(choices=[('P', 'درانتظار'), ('A', 'تایید شده'), ('R', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت کلی')),
                ('validated_at', models.DateTimeField(blank=True, help_text='زمان تایید شرکت توسط ادمین.', null=True, verbose_name='تاریخ تایید')),
                ('validation_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'وضعیت شرکت',
                'verbose_name_plural': 'وضعیت شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='FirstItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('icon', models.FileField(blank=True, null=True, upload_to='Companies/items/first/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'آیتم یک',
                'verbose_name_plural': 'آیتم های یک',
            },
        ),
        migrations.CreateModel(
            name='SecondItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('icon', models.FileField(blank=True, null=True, upload_to='Companies/items/second/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'آیتم دو',
                'verbose_name_plural': 'آیتم های دو',
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه'), ('saturday', 'شنبه'), ('sunday', 'یکشنبه')], max_length=10, verbose_name='روز هفته')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تعطیل بودن')),
            ],
            options={
                'verbose_name': 'روز کاری',
                'verbose_name_plural': 'روزهای کاری',
            },
        ),
    ]
