# Generated by Django 5.2 on 2025-05-27 07:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'حسابدار',
                'verbose_name_plural': 'حسابداران',
            },
        ),
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='Card number must consist of exactly 16 digits.', regex='^\\d{16}$')], verbose_name='شماره کارت')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='مالک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'کارت شرکت',
                'verbose_name_plural': 'کارت های شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='CompanyExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('IH', 'In House Service'), ('CP', 'Company Service'), ('BO', 'Both')], default='CP', max_length=2, verbose_name='نوع سرویس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'متخصص',
                'verbose_name_plural': 'متخصصان',
            },
        ),
        migrations.CreateModel(
            name='CompanyFirstItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'آیتم اول شرکت',
                'verbose_name_plural': 'آیتم های اول شرکت',
            },
        ),
        migrations.CreateModel(
            name='CompanyReceptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'منشی',
                'verbose_name_plural': 'منشی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CompanySecondItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'آیتم دوم شرکت',
                'verbose_name_plural': 'آیتم های دوم شرکت',
            },
        ),
        migrations.CreateModel(
            name='CompanyValidationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='Companies/Validations/', verbose_name='جواز کسب')),
                ('business_license_status', models.BooleanField(default=False, verbose_name='جواز کسب')),
                ('overall_status', models.CharField(choices=[('P', 'درانتظار'), ('A', 'تایید شده'), ('R', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت کلی')),
                ('validated_at', models.DateTimeField(blank=True, help_text='زمان تایید شرکت توسط ادمین.', null=True, verbose_name='تاریخ تایید')),
                ('validation_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'وضعیت شرکت',
                'verbose_name_plural': 'وضعیت شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MO', 'دوشنبه'), ('TU', 'سه\u200cشنبه'), ('WE', 'چهارشنبه'), ('TH', 'پنج\u200cشنبه'), ('FR', 'جمعه'), ('SA', 'شنبه'), ('SU', 'یکشنبه')], max_length=10, verbose_name='روز هفته')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تعطیل بودن')),
            ],
            options={
                'verbose_name': 'روز کاری',
                'verbose_name_plural': 'روزهای کاری',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام شرکت')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='لوگو')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='company/banners/', verbose_name='بنر')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='ویدئوی معرفی')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تأسیس')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینک LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='لینک Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک Instagram')),
                ('service_type', models.CharField(choices=[('IHS', 'خدمات در منزل'), ('ICS', 'خدمات در شرکت'), ('BOT', 'هر دو')], default='ICS', max_length=3, verbose_name='نوع خدمات')),
                ('is_validated', models.BooleanField(default=False, help_text='در صورت True بودن، شرکت توسط ادمین تایید شده است.', verbose_name='تایید شده توسط ادمین')),
                ('is_off_season', models.BooleanField(default=False, verbose_name='فصل تعطیلات / غیر کاری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_companies', to='Addresses.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
    ]
