# Generated by Django 5.2 on 2025-05-27 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Addresses', '0002_initial'),
        ('Companies', '0001_initial'),
        ('Industries', '0001_initial'),
        ('Items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیرعامل'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Industries.industry', verbose_name='صنعت'),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_companies', to='Addresses.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='companyaccountant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountants', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='companyaccountant',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_company', to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
        migrations.AddField(
            model_name='companycard',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_card', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='companyexpert',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='companyexpert',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_company', to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
        migrations.AddField(
            model_name='companyfirstitem',
            name='compay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_first_item', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='companyfirstitem',
            name='first_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_first_item', to='Items.firstitem', verbose_name='آیتم'),
        ),
        migrations.AddField(
            model_name='companyreceptionist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionists', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='companyreceptionist',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_company', to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
        migrations.AddField(
            model_name='companyseconditem',
            name='compay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_second_item', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='companyseconditem',
            name='second_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_second_item', to='Items.seconditem', verbose_name='آیتم'),
        ),
        migrations.AddField(
            model_name='companyvalidationstatus',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_status', to='Companies.company', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='companyvalidationstatus',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='ادمینی که شرکت را تایید کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_companies', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط'),
        ),
        migrations.AddField(
            model_name='workday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='Companies.company', verbose_name='شرکت مربوطه'),
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('company', 'day_of_week')},
        ),
    ]
