# Generated by Django 5.2 on 2025-05-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='day_of_week',
            field=models.CharField(choices=[('MO', 'دوشنبه'), ('TU', 'سه\u200cشنبه'), ('WE', 'چهارشنبه'), ('TH', 'پنج\u200cشنبه'), ('FR', 'جمعه'), ('SA', 'شنبه'), ('SU', 'یکشنبه')], max_length=10, verbose_name='روز هفته'),
        ),
    ]
