# Generated by Django 5.2 on 2025-05-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0003_alter_workday_day_of_week'),
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfirstitem',
            name='first_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_first_item', to='Items.firstitem', verbose_name='آیتم'),
        ),
        migrations.AlterField(
            model_name='companyseconditem',
            name='second_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_second_item', to='Items.seconditem', verbose_name='آیتم'),
        ),
        migrations.DeleteModel(
            name='FirstItem',
        ),
        migrations.DeleteModel(
            name='SecondItem',
        ),
    ]
