# Generated by Django 5.2 on 2025-04-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0003_companyemployee'),
        ('Industries', '0002_serviceindustry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Industries.industry', verbose_name='صنعت'),
            preserve_default=False,
        ),
    ]
