# Generated by Django 5.2 on 2025-05-01 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0004_company_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه'), ('saturday', 'شنبه'), ('sunday', 'یکشنبه')], max_length=10, verbose_name='روز هفته')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تعطیل بودن')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='Companies.company', verbose_name='شرکت مربوطه')),
            ],
            options={
                'verbose_name': 'روز کاری',
                'verbose_name_plural': 'روزهای کاری',
                'unique_together': {('company', 'day_of_week')},
            },
        ),
    ]
