# Generated by Django 5.2 on 2025-05-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0004_alter_companyfirstitem_first_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAddress',
        ),
    ]
