# Generated by Django 5.2 on 2025-05-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0005_workday'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_off_season',
            field=models.BooleanField(default=False, verbose_name='فصل تعطیلات / غیر کاری'),
        ),
    ]
