# Generated by Django 5.2 on 2025-05-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0006_company_address_company_city_company_province'),
        ('Services', '0003_delete_serviceemployee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyEmployee',
        ),
    ]
