# Generated by Django 5.2 on 2025-05-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0006_company_is_off_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service_type',
            field=models.CharField(choices=[('IHS', 'خدمات در منزل'), ('ICS', 'خدمات در شرکت'), ('BOT', 'هر دو')], default='ICS', max_length=3, verbose_name='نوع خدمات'),
        ),
    ]
