# Generated by Django 5.2 on 2025-05-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0007_company_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='companyvalidationstatus',
            name='compliance_certificate',
        ),
        migrations.RemoveField(
            model_name='companyvalidationstatus',
            name='compliance_certificate_status',
        ),
        migrations.RemoveField(
            model_name='companyvalidationstatus',
            name='safety_clearance',
        ),
        migrations.RemoveField(
            model_name='companyvalidationstatus',
            name='safety_clearance_status',
        ),
        migrations.RemoveField(
            model_name='companyvalidationstatus',
            name='tax_certificate',
        ),
        migrations.RemoveField(
            model_name='companyvalidationstatus',
            name='tax_certificate_status',
        ),
    ]
