# Generated by Django 5.2 on 2025-05-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0009_firstitem_seconditem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': 'شرکت ها'},
        ),
    ]
