# Generated by Django 5.2 on 2025-05-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0003_city_province_recipientaddress_city_city_province'),
        ('Companies', '0012_alter_companyvalidationstatus_business_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.city', verbose_name='شهر')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.company', verbose_name='خدمات گیرنده')),
            ],
            options={
                'verbose_name': 'آدرس مشتری',
                'verbose_name_plural': 'آدرس های مشتری ها',
            },
        ),
    ]
