# Generated by Django 5.2 on 2025-05-24 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='کیفیت')),
                ('behavior', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='رفتار')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='سرعت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت امتیاز')),
            ],
            options={
                'verbose_name': 'امتیاز سرویس',
                'verbose_name_plural': 'امتیازات سرویس',
            },
        ),
    ]
