# Generated by Django 5.2 on 2025-04-28 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services', '0003_recepientservicerequest_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='کیفیت')),
                ('behavior', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='رفتار')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='سرعت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت امتیاز')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Services.recepientservicerequest', verbose_name='درخواست سرویس')),
            ],
            options={
                'verbose_name': 'امتیاز سرویس',
                'verbose_name_plural': 'امتیازات سرویس',
            },
        ),
    ]
