# Generated by Django 5.2 on 2025-05-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scores', '0001_initial'),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescore',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Services.service', verbose_name='سرویس'),
        ),
    ]
